create table pictures (
    id      BIGINT generated by default as identity primary key,
    picture BYTEA

);

drop table if exists users;
CREATE TABLE users
(
    id          BIGINT generated by default as identity primary key,
    username    TEXT,
    password    TEXT,
    firstName   TEXT,
    lastName    TEXT,
    phone       TEXT,
    picture_id  int references pictures(id),
    userRole    SMALLINT NOT NULL    -- enum UserType
);

drop table if exists  ads;
create table ads (
    id          BIGINT generated by default as identity primary key,
    author      int REFERENCES users (id),
    price       int,
    title       text,
    picture_id  int references pictures(id)
);

drop table if exists  comments;
create table comments (
    id          BIGINT generated by default as identity primary key,
    author      int REFERENCES users (id),
    text        text
);

drop table if exists  ads_comments;
create table ads_comments (
    ads_id      int REFERENCES ads (id),
    comment_id  int REFERENCES comments (id)
);