-- liquibase formatted sql

-- changeset aleksey:1

-- table users
CREATE TABLE users
(
    id         INTEGER generated by default as identity primary key,
    username   TEXT,
    email      TEXT,
    password   TEXT,
    first_name TEXT,
    last_name  TEXT,
    phone      TEXT,
    image      TEXT,
    user_role  VARCHAR -- enum Role
);

-- table ads
CREATE TABLE ads
(
    id          INTEGER generated by default as identity primary key,
    author_id   int REFERENCES users (id),
    price       int,
    title       text,
    image_path  text,
    description text
);

-- table comments
CREATE TABLE comments
(
    id        INTEGER generated by default as identity primary key,
    author_id int, --REFERENCES users (id),
    ad_id     int, --REFERENCES ads (id),
    text      text,
    create_at timestamp
);
