-- liquibase formatted sql

-- changeset aleksey:1

CREATE TABLE users
(
    id         INTEGER generated by default as identity primary key,
    username   TEXT,
    email      TEXT,
    password   TEXT,
    first_name TEXT,
    last_name  TEXT,
    phone      TEXT,
    image      TEXT,
    user_role  VARCHAR -- enum Role
);

create table ads
(
    id          INTEGER generated by default as identity primary key,
    author_id   int REFERENCES users (id),
    price       int,
    title       text,
    image       text,-- REFERENCES pictures (id),
    image_path  text,
    description text
);

create table comments
(
    id        INTEGER generated by default as identity primary key,
    author_id int, --REFERENCES users (id),
    ad_id     int, --REFERENCES ads (id),
    text      text,
    create_at timestamp
);

create table pictures
(
    id          text primary key,
    data        oid
);